# Jekyll configuration for GitHub Pages
title: PostQuantum-Feldman-VSS
description: Post-Quantum Secure Feldman's Verifiable Secret Sharing
theme: minima  # Or jekyll-theme-minimal, or another supported theme

# Build settings
markdown: kramdown
plugins:
  - jekyll-relative-links

# Process these files as Jekyll files
include:
  - "../docs/"
  - "../README.md"
  - "../SECURITY.md"
  - "../CODE_OF_CONDUCT.md" 
  - "../CONTRIBUTING.md"
  - "../LICENSE"
  - "../index.md" # Ensure index.md is included

# Relative links configuration
relative_links:
  enabled: true
  collections: true