source "https://rubygems.org"

gem "jekyll", "~> 4.4.0"
gem "minima", "~> 2.5"  # Theme specified in your _config.yml

# Plugins
gem "jekyll-relative-links", "~> 0.7.0"
gem "jekyll-include-cache", "~> 0.2.1" # Optional: Improves build performance
gem "jekyll-redirect-from", "~> 0.16.0" # For redirects if needed

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 2.0"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2.0", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock Jekyll to v4 to prevent GitHub Pages gem from overwriting
gem "webrick", "~> 1.7" # Required for Ruby 3.0+