name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Setup Ruby
        id: setup-ruby
        uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f
        with:
          ruby-version: '3.4.2'
          bundler-cache: true
          
      - name: Install dependencies
        if: steps.setup-ruby.outputs.cache-hit != 'true'
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
        working-directory: ./site

      - name: Install Node.js
        uses: actions/setup-node@40337cb8f758cccdfe3475af609daa63f81c7e23
        with:
          node-version: 22.14.0

      - name: Cache npm global packages
        id: cache-npm-global
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') || github.sha }}
          restore-keys: |
            ${{ runner.os }}-npm-global-

      - name: Debug cache outputs
        run: echo "Cache hit is ${{ steps.cache-npm-global.outputs.cache-hit }}"

      - name: Install Wrangler
        if: steps.cache-npm-global.outputs.cache-hit != 'true'
        run: npm install -g wrangler

      - name: Build site
        run: |
          bundle exec jekyll build --source $GITHUB_WORKSPACE --destination $GITHUB_WORKSPACE/site/build --config $GITHUB_WORKSPACE/site/_config.yml --verbose
        working-directory: ./site
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: site-build
          path: site/build
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: site-build
          path: site/build

      - name: Install Node.js
        uses: actions/setup-node@40337cb8f758cccdfe3475af609daa63f81c7e23
        with:
          node-version: 22.14.0
          
      - name: Cache npm global packages
        id: cache-npm-global
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-global-${{ hashFiles('**/package-lock.json') || github.sha }}
          restore-keys: |
            ${{ runner.os }}-npm-global-

      - name: Install Wrangler
        if: steps.cache-npm-global.outputs.cache-hit != 'true'
        run: npm install -g wrangler

      - name: Publish
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy site/build --project-name=postquantum-feldman-vss