name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - name: Setup Ruby
        uses: ruby/setup-ruby@1a615958ad9d422dd932dc1d5823942ee002799f
        with:
          ruby-version: '3.4.2'
          cache: bundler
          
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: site

      - name: Build site
        run: |
          bundle exec jekyll build
        working-directory: site

      - name: Publish
        uses: cloudflare/wrangler-action@707f63750981584eb6abc365a50d441516fb04b8
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          command: pages deploy site/_site --project-name=postquantum-feldman-vss
        env:
          NODE_VERSION: 20.19.0
          WRANGLER_VERSION: 3.90.0