# .github/workflows/pypi-publish.yml
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-n-publish:
    name: pypi-publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    
    - name: Build a binary wheel and a source tarball
      run: |
        hatch build

    - name: Publish distribution 📦 to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@db8f07d3871a0a180efa06b95d467625c19d5d5f
      with:
        print-hash: true
        verbose: true
