# .github/workflows/pypi-publish.yml
name: Publish Python 🐍 distributions 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  # Allows to run this workflow manually from the Actions tab on GitHub UI
  workflow_dispatch:

jobs:
  build-n-publish:
    name: pypi-publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/PostQuantum-Feldman-VSS
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.2"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch  # Install the build tool (Hatch)

    - name: Build a binary wheel and a source tarball
      run: |
        hatch build

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
