name: Sign Release Artifacts

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (including your package in editable mode)
        run: |
          python -m pip install --upgrade pip
          pip install -e .  

      - name: Sign Script with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: feldman_vss.py README.md LICENSE pyproject.toml
          release-signing-artifacts: true
          upload-signing-artifacts: true
      - name: Verify Signature
        if: always()
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: feldman_vss.py README.md LICENSE pyproject.toml
          verify: true
