name: Sign Release Artifacts

on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@5db1cf9a59fb97c40a68accab29236f0da7e94db
        with:
          python-version: '3.13.5'

      - name: Install dependencies (including your package in editable mode)
        run: |
          python -m pip install .
          python -m pip install --upgrade pip

      - name: Sign Script with Sigstore
        uses: sigstore/gh-action-sigstore-python@6409abb6b6aa159c173b7ccfc47078bec5735676
        with:
          inputs: feldman_vss.py README.md SECURITY.md LICENSE pyproject.toml
          release-signing-artifacts: true
