name: Sign Release Artifacts

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: '3.13.2'

      - name: Install dependencies (including your package in editable mode)
        run: |
          python -m pip install .
          python -m pip install --upgrade pip

      - name: Sign Script with Sigstore
        uses: sigstore/gh-action-sigstore-python@300d3393a8effd58cc9e99f701c7c7238fb517d2
        with:
          inputs: feldman_vss.py README.md SECURITY.md LICENSE pyproject.toml
          release-signing-artifacts: true
